#!/usr/bin/env bash

set -x

if [[ -z "$XDG_CONFIG_HOME" ]]; then
    XDG_CONFIG_HOME=$HOME/.config
fi

if [[ -z "$XDG_RUNTIME_DIR" ]]; then
    XDG_RUNTIME_DIR="/tmp"
fi
export LIBEI_SOCKET=$XDG_RUNTIME_DIR/eis-0

client_config_file=$XDG_CONFIG_HOME/barrier/server.name
server_config_file=$XDG_CONFIG_HOME/barrier/barriers.conf

if [[ -e $client_config_file ]]; then
    exec barrierc --no-daemon --disable-crypto $(cat $client_config_file)
fi

if [[ -e $server_config_file ]]; then
    exec barriers --no-daemon --name $HOSTNAME --disable-crypto -c $server_config_file
fi

echo "Neither config file found"
exit 1
